# Site settings
title: "Gerrit Code Review"
description: "The world's most powerful code review platform for Git-based development"
url: "https://www.gerritcodereview.com"
baseurl: ""
topnav_title: "Gerrit Code Review"

# Permalinks
permalink: /:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      search: true
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      search: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: plaintext

# Exclude files from processing
exclude:
  - .idea/
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Dockerfile
  - docker-compose.yml
  - docker-entrypoint.sh
  - createtag
  - firebase-debug.log
  - pdf-all.sh
  - pdf-mydoc.sh
  - pdf-product1.sh
  - pdf-product2.sh
  - update.sh
  - _site/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata

# Build settings
destination: _site
incremental: false

# Google Analytics
google_analytics: "G-XXXXXXXXXX" # Replace with your actual GA4 tracking ID
