# Site settings
topnav_title: Gerrit Code Review
title: "Gerrit Code Review"
baseurl: ""

google_analytics: G-RGG5V63F81
# if you have google-analytics ID, put it in. if not, edit this value to blank.

host: 127.0.0.1
# the preview server used. Leave as is.

port: 4000
# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.

# Permalinks
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude files from processing
exclude:
  - .idea/
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Dockerfile
  - docker-compose.yml
  - docker-entrypoint.sh
  - createtag
  - firebase-debug.log
  - pdf-all.sh
  - pdf-mydoc.sh
  - pdf-product1.sh
  - pdf-product2.sh
  - update.sh
  - _site/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata

# Build settings
destination: _site
incremental: false

# Markdown settings
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
 syntax_highlighter_opts:
   default_lang: plaintext

# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      search: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      search: true

description: "The world's most powerful code review platform for Git-based development"

# needed for sitemap.xml file only
url: "https://www.gerritcodereview.com"