# Site settings
title: "Gerrit Code Review"
description: "The world's most powerful code review platform for Git-based development"
url: "https://www.gerritcodereview.com"
baseurl: ""
topnav_title: "Gerrit Code Review"

# Site Author
author:
  name: "Gerrit Code Review"
  avatar: "/images/gerrit-logo.png"
  bio: "The world's most powerful code review platform"
  location: "Open Source"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/GerritCodeReview/gerrit"
    - label: "Documentation"
      icon: "fas fa-fw fa-book"
      url: "https://gerrit-review.googlesource.com/Documentation/"

# Site Footer
footer:
  links:
    - label: "Documentation"
      icon: "fas fa-fw fa-book"
      url: "https://gerrit-review.googlesource.com/Documentation/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/GerritCodeReview/gerrit"
    - label: "Community"
      icon: "fas fa-fw fa-users"
      url: "https://groups.google.com/group/repo-discuss"

# Collections
collections:
  tooltips:
    output: false

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      search: true
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      search: true
  - scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      search: true
      tooltip: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: plaintext

# Exclude files from processing
exclude:
  - .idea/
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Dockerfile
  - docker-compose.yml
  - docker-entrypoint.sh
  - createtag
  - firebase-debug.log
  - pdf-all.sh
  - pdf-mydoc.sh
  - pdf-product1.sh
  - pdf-product2.sh
  - update.sh
  - _site/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata

# Build settings
destination: _site
incremental: false

# Minimal Mistakes specific settings
masthead_title: "Gerrit Code Review"
logo: "/images/favicon.ico"

# Search
search: true
search_full_content: true

# Comments
comments:
  provider: false

# Page layout
read_time: false
words_per_minute: 200

# Social sharing
share: true
share_date: true

# Related posts
related: true

# Pagination
paginate: 5
paginate_path: "/page-:num/"

# SEO
title_separator: "|"
description: "The world's most powerful code review platform for Git-based development"
keywords: ["code review", "git", "gerrit", "development", "collaboration"]
author: "Gerrit Code Review"
