node("jekyll") {
    checkout scm
    stage("fetch plugins page") {
        // Reuse the latest plugins.md generated by the homepage-plugins
        // job instead of regenerating it here (that takes hours). This
        // step fails the build if homepage-plugins has never succeeded,
        // so we never deploy without a plugins page.
        copyArtifacts(
            projectName: "homepage-plugins",
            selector: lastSuccessful(),
            filter: "pages/site/plugins/plugins.md")
    }
    stage("build homepage") {
        sh "bundle install"
        sh "bundle exec jekyll build"
    }
    stage("deploy homepage") {
        withCredentials([string(credentialsId: "firebase", variable: "FIREBASE_TOKEN")]) {
            sh "firebase use default"
            sh "firebase deploy"
        }
    }
}
